### ISSUE TITLE
Unable to open the commit dialog in eclipse 2024-03 (4.31.0)

### ISSUE THREAD

**Issue by MikOfClassX** [JAndrassy/org.eclipse.team.cvs#5]
Here's the log:

```
eclipse.buildId=4.31.0.20240307-1200
java.version=21.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/C:/eclipse_workspace_rel-8_0/

org.eclipse.ui
Error
Thu Mar 14 11:13:46 CET 2024
Unhandled event loop exception

java.lang.IllegalArgumentException: -1
	at org.eclipse.team.internal.ui.SWTUtils.createGridLayout(SWTUtils.java:222)
	at org.eclipse.team.internal.ccvs.ui.wizards.CommitWizardCommitPage.createControl(CommitWizardCommitPage.java:113)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:180)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:744)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:637)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1092)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.team.internal.ccvs.ui.wizards.CommitWizard.open(CommitWizard.java:433)
	at org.eclipse.team.internal.ccvs.ui.wizards.CommitWizard.run(CommitWizard.java:426)
	at org.eclipse.team.internal.ccvs.ui.wizards.CommitWizard.run(CommitWizard.java:356)
	at org.eclipse.team.internal.ccvs.ui.mappings.AbstractCommitAction.execute(AbstractCommitAction.java:66)
	at org.eclipse.team.internal.ccvs.ui.mappings.CVSModelProviderAction.run(CVSModelProviderAction.java:128)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:171)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:415)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

```

**Comment by JAndrassy** [comment]
it is a bug in Eclipse https://github.com/eclipse-platform/eclipse.platform/commit/d2ed9d5ce7f06e0620f57537d835836555708a2a#r139829705

**Comment by MikOfClassX** [comment]
yup. Waiting for the fix.

**Comment by xberkhout** [comment]
Same problem here.

**Comment by JAndrassy** [comment]
so the fix https://github.com/eclipse-platform/eclipse.platform/pull/1254 is merged, but I guess we will have to wait for 2024-06

**Comment by MikOfClassX** [comment]
Hey, it's fixed with Eclipse Staging 2024-06 !

**Comment by aLiEnHeAd13** [comment]
Eclipse IDE 2024-06 was released:
https://www.eclipse.org/downloads/
